### ISSUE TITLE
Lanscape mode UI issues

### ISSUE THREAD

**Issue by GNUuser** [a-dekker/smpc#11]
![Captura_20200503_001](https://user-images.githubusercontent.com/45316884/80929043-f5570680-8d76-11ea-9937-d8f8b25bd3be.png)

**Comment by a-dekker** [comment]
I am familiar with this issue. It rarely occurs when you rotate from portrait to landscape, right?

I'ts not an issues related to SMPC, but some kind of Sailfish bug. It can also happen in other apps, see for example https://yadi.sk/i/uYY9gnWQqIi8qQ

Maybe it's worth posting about it on together.jolla.com ?

**Comment by a-dekker** [comment]
Question created of TJC: https://together.jolla.com/question/226813/rotation-from-portrait-to-landscape-sometimes-creates-artifacts/

**Comment by GNUuser** [comment]
Thank you A-dekker.

**Comment by GNUuser** [comment]
![Captura_20200504_001](https://user-images.githubusercontent.com/45316884/80988450-8a064680-8e01-11ea-9bd9-79963a722ff0.png)
![Captura_20200504_002](https://user-images.githubusercontent.com/45316884/80988454-8a9edd00-8e01-11ea-91ce-c8981f62dbbb.png)
![Captura_20200504_003](https://user-images.githubusercontent.com/45316884/80988455-8a9edd00-8e01-11ea-90fd-b72995b1bdef.png)

**Comment by GNUuser** [comment]
Storeman show slightly same issue.

**Comment by GNUuser** [comment]
In storeman show artifacts with keyboard up in portrait not in landscape.

**Comment by a-dekker** [comment]
The Storeman issue is another matter. That is just a layout/aligning issue caused by some of the latest releases. And it is a consistent issue, not random.

**Comment by GNUuser** [comment]
Yes i agreed.
