### ISSUE TITLE
Add more playback modes (consume, single, oneshot)

### ISSUE THREAD

**Issue by fuchsmich** [a-dekker/smpc#13]
For now we got shuffle and repeat, but there are more modes:

https://www.musicpd.org/doc/html/protocol.html#playback-options

- c++-part will be done by me
- in qml we need to redesign the [playback controls](https://github.com/a-dekker/smpc/blob/master/qml/components/PlaybackControls.qml). We need additional switches and place them nicely.
- we need icons
  - onehot: could be the char "1"
  - consume: cantata uses [pacman](https://github.com/CDrummond/cantata/blob/master/icons/consume.svg), which I like
  - single??

**Comment by a-dekker** [comment]
I was not aware of any existing consume toggle, never noticed it in Cantata.
The playback control is already quite stacked, so there is a challenge in a potential redesign.

**Comment by a-dekker** [comment]
Or we have to view it as global preference, so it can be placed in a settings page.

**Comment by fuchsmich** [comment]
It should be quickly accessible.

**Comment by a-dekker** [comment]
To me, it's looks more like a preference. I want to have played items removed from my playlist, or I don't. For now I can't see why I want to switch that behavior frequently. But then again, I never used this option, so I might be a bad judge.

**Comment by GNUuser** [comment]
I definitely want pacman in the playback controls. I will collaborate with the pizzas and energy drinks. 
:  )

**Comment by fuchsmich** [comment]
It's actually two modes: consume and single.

consume can be on and off

single is tristate: on, off, oneshot.

**Comment by a-dekker** [comment]
As progress seems to be stalled in general I made some changes to make it visible for users.
I still think playback options are used rarely in general, so I decided to create a playback settings page with all the playback settings, including the ones already present in the playback controls.
The already implemented single playback backend had some issues. It can now successfully be switched on and off, but I am not sure if it handles all the repeat/oneshot states correctly. I am not planning on using this option, as I see no use for it for myself.

If there there is no further intention on alternative implementations with shiny pacman icons etc I suggest we close this issue.

Related commit: https://github.com/a-dekker/smpc/commit/016b691857d6d6660f991bb00e66c0ed43ebe7b6

**Comment by GNUuser** [comment]
I wish a Shiny Pacman lookable. I know YOU CAN @fuchsmich

**Comment by fuchsmich** [comment]
I don't think it's usefull to burry playback modes somewhere in the settings. This should be placed next to all the other playback controls, as in every other media player. But it's ok to keep it like this for now.

The mpd dev himself doesnt know what "[oneshot](https://github.com/MusicPlayerDaemon/MPD/issues/539)" is for, so maybe we can skip this mode altogether.

**Comment by a-dekker** [comment]
Then I'll close it as implemented. And if you manage to squeeze it all in the playback control panel submit a PR.

**Comment by GNUuser** [comment]
Oneshot means play only 1 song/folder then stop Automatically ?

**Comment by a-dekker** [comment]
> Oneshot means play only 1 song/folder then stop Automatically ?

I added description to the playback settings in SMPC. Maybe first read that, specifically the "Single playback" description.
