### ISSUE TITLE
Add "Play stream" option

### ISSUE THREAD

**Issue by smihai** [a-dekker/smpc#14]
Like some desktop clients (like gmpc, sonata) it would be interesting to be able to play an external audio stream. For example to listen to a webradio or a podcast.

**Comment by fuchsmich** [comment]
Could you elaborate the workflow?

**Comment by smihai** [comment]
My use case is: I go to my favourite webradios site, or a podcast directory and I want to listen to one of them on my MPD. So I copy/paste the stream URL and let mpd play it.

**Comment by a-dekker** [comment]
Never used it so I can't tell if it is useful, but the playlist has an "Add url" option.

**Comment by smihai** [comment]
Indeed, that's my use case. Thanks!
I close the issue.
