### ISSUE TITLE
main menu - configureable button

### ISSUE THREAD

**Issue by fuchsmich** [a-dekker/smpc#18]
The main menu has two columns, so it would be nicer, if it had an even number of buttons.

What if we made a configurable 8th button?

Options could be:

- show saved playlists
- shuffle and play all tracks
- shuffle and play a specific saved playlist
- ...?

**Comment by a-dekker** [comment]
On the Jolla tablet, we would need two new buttons to make it even (it has three columns). But that has an extremely small user base.

Can't think of any option I would need, but feel free to make use of the empty space it is now.

**Comment by a-dekker** [comment]
If you don't mind I am going to extract the changes from your draft pull request regarding the main menu buttons. And simple add the About button as extra button for now.

**Comment by a-dekker** [comment]
https://github.com/a-dekker/smpc/commit/903c75e577bd80de28e8bf91302b9b5241f4fe6e for the change in the main menu buttons.

**Comment by a-dekker** [comment]
Even numbers implemented, no plans for configurable buttons from my side.
