### ISSUE TITLE
More server and database details

### ISSUE THREAD

**Issue by a-dekker** [a-dekker/smpc#19]
One thing I do like about Cantata is that I can get more Server information from the current connection:
- Protocol
- Uptime

And from the current database I miss:
- Total songs
- Total duration
- Last updated

If easy to retrieve the latter could be added to the database settings.
Server info could be a separate menu line in the settings.

**Comment by fuchsmich** [comment]
Sure, no problem.

**Comment by a-dekker** [comment]
I am going to give it a go myself.

**Comment by a-dekker** [comment]
It's easy to retrieve the data, but passing it to QML to correct way keeps giving me headaches. I'm done for now, already spend way too much time on this.

**Comment by fuchsmich** [comment]
Did you make any changes? can you push them into a new branch?

**Comment by a-dekker** [comment]
I reverted most of the changes. There is a part in networkaccess.cpp that might be usable again. I could do a bit of a cleanup and create a new branch if you are interested in having a look at it.
