### ISSUE TITLE
Need fix an UI layout

### ISSUE THREAD

**Issue by GNUuser** [a-dekker/smpc#23]
![Captura_20200612_002_edit](https://user-images.githubusercontent.com/45316884/84554413-aee5b780-ace5-11ea-8ef2-341a507d318e.png)

**Comment by a-dekker** [comment]
That is the custom "speedscroller" for navigating though a page. It gets activated once you start scrolling on a page. You will see this on almost all pages, like album or artist list.
In case you don't know how it works, go to the album page, put your finger in the middle of the right border site and start moving your finger up or down. Then the speedscrolling gets activated.

**Comment by GNUuser** [comment]
Yeah but it look a bad desing because not have arrows signs or something. If it is  a old scroll it need delete it, and put regular Sailfish scroll desing.

**Comment by a-dekker** [comment]
It's largely a matter of taste. Here is a comment from a fan of the current speedscroller: https://openrepos.net/comment/30847#comment-30847
One of the things I like about it, is that I can go to the middle of a large list with ease. That's not possible with the default scroll functionality.

For now I am not planning to change this. Maybe it can be evaluated later on what pages it is relevant and on that pages it is not.

**Comment by GNUuser** [comment]
I never seen before that scroll, may be it useful, But when the pulley menu is down for options, that rare scroll has to be OFF.

**Comment by GNUuser** [comment]
@a-dekker do you want contribute here: https://github.com/koso00/depecher/issues/4 You are a good UI desing dev.

**Comment by a-dekker** [comment]
> I never seen before that scroll, may be it useful, But when the pulley menu is down for options, that rare scroll has to be OFF.

That may be hard to implement, but I can agree with you on that.

**Comment by a-dekker** [comment]
Wasn't that hard, fixed by https://github.com/a-dekker/smpc/commit/e2da8428aa1a85bf5d9ed7726e9bb019b54da3fc

**Comment by GNUuser** [comment]
> Wasn't that hard, fixed by [e2da842](https://github.com/a-dekker/smpc/commit/e2da8428aa1a85bf5d9ed7726e9bb019b54da3fc)

Thank you.
 You are fast & great dev. :  )
