### ISSUE TITLE
 There is a empty pulley menu.

### ISSUE THREAD

**Issue by GNUuser** [a-dekker/smpc#30]
![Captura_20200702_001](https://user-images.githubusercontent.com/45316884/86415645-ab66a000-bc95-11ea-9aef-04f96046c584.png)

**Comment by a-dekker** [comment]
fixed by https://github.com/a-dekker/smpc/commit/858bafbcaa2a3b52bda8d4bc5cd8b7847a0660a4

**Comment by GNUuser** [comment]
Thank  you @a-dekker you always ShutDown FAST the pesky bugs. :  )
But there is still  a bug: pulley menu is on when is empty.

**Comment by a-dekker** [comment]
I'll have a look at that also.

**Comment by a-dekker** [comment]
Empty pulley menu hidden on currentsong page via https://github.com/a-dekker/smpc/commit/f791a5803fdab695b440301b58de57e08dae4f89
