### ISSUE TITLE
FR: sepate string to translate separately.

### ISSUE THREAD

**Issue by GNUuser** [a-dekker/smpc#33]
![Captura_20200711_003](https://user-images.githubusercontent.com/45316884/87230936-09c00c80-c381-11ea-8677-57ca29016b6b.png)

**Comment by GNUuser** [comment]
HI dev,
My translation is broke ATM. Can you push this changes please.

**Comment by a-dekker** [comment]
There is no broken translation. The fact that you want to separate those two is a personal preference, I was fine with both being the same.
Anyway, I removed the custom dialog accept text so it has the default text value now (just like the cancel value already has).

change https://github.com/a-dekker/smpc/commit/7431ef12f5fe9d6cafd9fd348f3f78539463250b

**Comment by GNUuser** [comment]
Thank you @a-dekker
 You're a genius!
