### ISSUE TITLE
Some  bad design.

### ISSUE THREAD

**Issue by GNUuser** [a-dekker/smpc#8]
To reproduce: Settings -> Database -settings

![Captura_202ADE-SMPC21_001_edit_edit](https://user-images.githubusercontent.com/45316884/79933250-8942dd00-841d-11ea-8dee-cab03bc2f718.png)

**Comment by a-dekker** [comment]
You point to a row of buttons without any further comment. What's the design problem?

**Comment by GNUuser** [comment]
The 6 options are very close to each other, this can cause an error when marking one with the other.

**Comment by a-dekker** [comment]
Never had issues with touching the wrong button, but on the other hand I crossed my mind to do some layout changes to this page. So I'll have a look at that.

**Comment by GNUuser** [comment]
I just reporting ...bad looks.

**Comment by GNUuser** [comment]
In fact, the original author accepted having created SMPC with pure hammer blows, that is why it is somewhat messy.

**Comment by a-dekker** [comment]
Changed by commit https://github.com/a-dekker/smpc/commit/2f06ddc8f2accb1b41226ede2c51b7130cfc8888

And released in version 1.3.9-1.

**Comment by GNUuser** [comment]
Whohoo!!! It looks good now, also English strings are more optimized for portrait mode display.  Thank you Ade, you are a Hero. :  )
